#!/bin/sh

# ask for root using pkexec 
if [ "$(id -u)" -ne 0 ]; then #id not 0 means not root
    exec pkexec "$0" "$@"
fi

#suspend command wrapper 
delay=20 #below 15 causes issues #going below 15 has caused rtc to be labelled as manual (-s 10 when tested) 
#time based detection
secnow=$(date +%s)
secafterdelay=$((secnow + delay))

rtcwake -m mem -s $delay > /dev/null #safe init time beacause entering suspend may/can take some time followed by timer job takeover 

secafterwake=$(date +%s) 
tolsecafterwake=$((secafterwake + 2)) #tolerance time needed for small interval rtcwakes

if [ $secafterdelay -lt $tolsecafterwake ]; then
touch /tmp/sulockfile
echo "completed delay, wrote lock"
else
echo "manually woke, no lock" #or by error
fi
#temporary lockfile is currently cleared by main script (help for testing edge cases needed)
