#!/bin/sh

#suspend command wrapper 
delay=20 #below 15 causes issues
#time based detection
secnow=$(date +%s)
secafterdelay=$((secnow + delay))

rtcwake -m mem -s $delay > /dev/null #safe init time beacause entering suspend may/can take some time then timer job takeover 

secafterwake=$(date +%s) 
tolsecafterwake=$((secafterwake + 2)) #tolerance time needed for small interval rtcwakes

if [ $secafterdelay -lt $tolsecafterwake ]; then
touch /tmp/sulockfile
echo "completed delay, wrote lock"
else
echo "manually woke, no lock" #or by error
fi
#going below 15 has caused rtc to be labelled as manual (-s 10 when tested) 
#also need to clean the temporary file (help needed here to avoid unexpected suspend loops)(currently done by manual detection in main script)
#dont add it here as after the 60 sec wake itll be cleared 
